### ISSUE TITLE
Retrieve subject information

### ISSUE THREAD

**Issue by TomRegan** [vv9k/mobi-rs#38]
This might be a feature or a doc request; taking [the Project Gutenberg edition of A Tale of Two Cities](https://www.gutenberg.org/ebooks/98) for reference, I'd like to be able to retrieve the tags or subjects from the mobi file. The result for this title would be the following list

| idx |Tag| 
|---|---|
|0|Historical fiction|
|1|France -- History -- Revolution, 1789-1799 -- Fiction|
|2|London (England) -- History -- 18th century -- Fiction|
|3|War stories|
|4|Executions and executioners -- Fiction|
|5|French -- England -- London -- Fiction|
|6|Lookalikes -- Fiction|
|7|British -- France -- Paris -- Fiction|
|8|Paris (France) -- History -- 1789-1799 -- Fiction|

Unfortunately I'm not familiar enough with the mobi format to find this data in the headers.

---

If you're familiar with libmobi, this would be the same functionality provided by [mobi_meta_get_subject](https://www.fabiszewski.net/libmobi/group__mobi__export.html#gaf408bf70e9c3f736c8fc3814ebad30ba).

**Comment by vv9k** [comment]
I added necessary changes in 28543519bd and 50f2db914eb. Example usage:
```rust
fn main() {
    match mobi::Mobi::from_path("book.mobi") {
        Ok(mobi) => {
            println!("{:#?}", mobi.metadata.subjects().unwrap_or_default());
        }
        Err(e) => eprintln!("{}", e),
    }
}
```

prints:
```
[
    "Historical fiction",
    "France -- History -- Revolution, 1789-1799 -- Fiction",
    "London (England) -- History -- 18th century -- Fiction",
    "War stories",
    "Executions and executioners -- Fiction",
    "French -- England -- London -- Fiction",
    "Lookalikes -- Fiction",
    "British -- France -- Paris -- Fiction",
    "Paris (France) -- History -- 1789-1799 -- Fiction",
]
```

**Comment by TomRegan** [comment]
I've tested the latest changeset and it works perfectly for me.

Thanks so much for this, I really appreciate it! 😄

**Comment by vv9k** [comment]
Glad to hear that it worked for you! :) Will release a new version soon.
