### ISSUE TITLE
New release with the panic fixes?

### ISSUE THREAD

**Issue by ivan** [vv9k/mobi-rs#41]
I confirmed that bb9e376862179a743030056b481018b3fefec08e fixed either

```
thread 'main' panicked at 'attempt to subtract with overflow', ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mobi-0.7.0/src/headers/exth.rs:231:43
```
or
```
thread 'main' panicked at 'attempt to subtract with overflow', ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mobi-0.7.0/src/headers/mobih.rs:304:42
```

for 73 real MOBI files, so it might be worth making a new release?

(Also, thank you very much for this library, I'm using it to detect which .mobi are Print Replica with a PDF inside.)

**Comment by vv9k** [comment]
Thanks for testing it out, I just uploaded updated version `0.8.0` to crates.
